#!/usr/bin/env ruby

# run doctl with access token secret
require 'util'

def main
  t = Util.config["digitalocean-access-token"]
  check_token_presence(t)

  `doct -t #{t} "$@"`
end

def check_token_presence(t)
  return true if t.present?
  puts "No token found; should be set as \"digitalocean-access-token\" " \
    "in config.json"
  exit(false)
end

main
