#!/bin/sh

# run doctl with access token secret
TOKEN=$(cat /root/secrets/digitalocean_access_token)
if [ -z $TOKEN]; then
  echo "No token found; should be in ~/secrets/digitalocean_access_token"
  exit 1
fi

doctl -t $TOKEN "$@"
